version: "3.7"

services:
  fake-survey-generator-api:
    image: ${DOCKER_REGISTRY-}fake-survey-generator-api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/server/FakeSurveyGenerator.API/Dockerfile
    depends_on:
      - sql-server

  fake-survey-generator-worker:
    image: ${DOCKER_REGISTRY-}fake-survey-generator-worker:${TAG:-latest}
    build:
      context: .
      dockerfile: src/server/FakeSurveyGenerator.Worker/Dockerfile
    depends_on:
      - sql-server
      - fake-survey-generator-api

  marcel-michau-idp:
    image: ${DOCKER_REGISTRY-}marcel-michau-idp:${TAG:-latest}
    build:
      context: .
      dockerfile: src/server/MarcelMichau.IDP/Dockerfile

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU1-ubuntu-16.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=<YourStrong!Passw0rd>

  redis:
    image: redis
