apiVersion: skaffold/v1beta14
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: marcelmichau/fakesurveygeneratorui
      context: .
      docker:
        dockerfile: src/client/ui/Dockerfile
    - image: marcelmichau/fakesurveygeneratorapi
      context: .
      docker:
        dockerfile: src/server/FakeSurveyGenerator.API/Dockerfile
    - image: marcelmichau/identityserver
      context: .
      docker:
        dockerfile: src/server/MarcelMichau.IDP/Dockerfile
deploy:
  helm:
    releases:
      - name: fake-survey-generator-ui
        chartPath: ./charts/fake-survey-generator-ui
        namespace: default
        values:
          image: marcelmichau/fakesurveygeneratorui
        imageStrategy:
          helm: {}
      - name: fake-survey-generator-api
        chartPath: ./charts/fake-survey-generator-api
        namespace: default
        values:
          image: marcelmichau/fakesurveygeneratorapi
        imageStrategy:
          helm: {}
      - name: identityserver
        chartPath: ./charts/identityserver
        namespace: default
        values:
          image: marcelmichau/identityserver
        imageStrategy:
          helm: {}
      - name: sql-server
        chartPath: ./charts/sql-server
        namespace: default
        imageStrategy:
          helm: {}
      - name: redis
        chartPath: ./charts/redis
        namespace: default
        imageStrategy:
          helm: {}
