apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: marcelmichau/fakesurveygeneratorui
      context: .
      docker:
        dockerfile: src/client/ui/Dockerfile
    - image: marcelmichau/fakesurveygeneratorapi
      context: .
      docker:
        dockerfile: src/server/FakeSurveyGenerator.API/Dockerfile
    - image: marcelmichau/identityserver
      context: .
      docker:
        dockerfile: src/server/MarcelMichau.IDP/Dockerfile
deploy:
  helm:
    releases:
      - name: fake-survey-generator
        chartPath: ./charts/fake-survey-generator
        namespace: default
        values:
          fake-survey-generator-ui.image: marcelmichau/fakesurveygeneratorui
          fake-survey-generator-api.image: marcelmichau/fakesurveygeneratorapi
          identityserver.image: marcelmichau/identityserver
        valuesFiles:
          - charts/fake-survey-generator/values.yaml
        imageStrategy:
          helm: {}
