replicaCount: 1

image:
  repository: marcelmichau/fakesurveygeneratorui
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: k8s.local
      paths:
        - /

  tls:
   - secretName: k8s-local-tls-secret
     hosts:
       - k8s.local

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
