apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: fake-survey-generator-api-test-identity-binding
spec:
  azureIdentity: aks-aad-pod-identity-test
  selector: aks-aad-pod-identity-test