apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: aks-aad-pod-identity-test
spec:
  type: 0
  resourceID: {{ .Values.azurePodIdentityResourceId }}
  clientID: {{ .Values.azurePodIdentityClientId }}