{{- if not .Values.api.config.azureRedisCacheEnabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}-redis
    helm.sh/chart: {{ include "..chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-redis
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "..name" . }}-redis
      app.kubernetes.io/instance: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "..name" . }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}-redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}-redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command: ["redis-server"]
          args: ["--requirepass", "{{ .Values.redis.config.password }}"]
          ports:
            - containerPort: 6379
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
