{{- if not .Values.api.config.azureDatabaseEnabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-database
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}-database
    helm.sh/chart: {{ include "..chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-database
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "..name" . }}-database
    app.kubernetes.io/instance: {{ .Release.Name }}-database
{{- end }}