apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}-ui-config-map
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    helm.sh/chart: {{ include "..chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nginx.conf: |
    events { }

    http {
        include mime.types;

        upstream api {
            server {{ include "..fullname" . }}-api:{{ .Values.api.service.port }};
        }

        server {
            listen {{ .Values.ui.service.port }};

            location /api {
                proxy_pass http://api;
            }
        }
    }