azureDatabaseEnabled: false
azureDatabaseUseActiveDirectoryAuthentication: false
databaseServer: sql-server
database: FakeSurveyGenerator
user: SA
password: <YourStrong!Passw0rd>
azureRedisCacheEnabled: false
redisUrl: redis
redisPassword: testing
redisDefaultDatabase: 0
identityProviderUrl: ""
azureApplicationInsightsEnabled: false # This can only be enabled when azureKeyVaultEnabled is true, as the instrumentation key is stored in Key Vault
azureKeyVaultEnabled: false
azureKeyVaultName: ""
azureKeyVaultResourceGroup: ""
azureKeyVaultSubscriptionId: ""
azureKeyVaultTenantId: ""
azurePodIdentityClientId: ""
azurePodIdentityResourceId: ""
azurePodIdentityName: ""

replicaCount: 1

image:
  repository: marcelmichau/fakesurveygeneratorapi
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: k8s.local
      paths:
        - /api
        - /swagger
        - /health

  tls:
   - secretName: k8s-local-tls-secret
     hosts:
       - k8s.local

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 300Mi

nodeSelector: {}

tolerations: []

affinity: {}
